### ISSUE TITLE
Converting to .txt and back to .bin causes game to crash, even if no changes have been made

### ISSUE THREAD

**Issue by WhitetailAni** [RoadrunnerWMC/nsmbw-staffroll-tool#3]
After sorting out the issues with converting the file, I've hit upon another - no matter the changes (if any), converting staffroll.bin to staffroll.txt and back to staffroll.bin causes the game to crash upon loading the credts, as soon as any text appears. Additionally, the first line will have some extra blocks attached to it, as shown by the attached image (stock credits file that has been converted to .txt and back to .bin).
I tested with major edits, with one edit, with no edits, etc., and everything points to your script. I tested the unedited and unconverted staffroll.bin file with my modified credits stage and it worked fine as well.
![image](https://user-images.githubusercontent.com/87622301/126925384-b99bdaa0-4279-491f-8c14-41dc40f61ad8.png)

**Comment by RoadrunnerWMC** [comment]
Try it with 1fd21d8?

**Comment by RoadrunnerWMC** [comment]
RealKGB confirmed in #2 that 1fd21d8 solved his problem, so, closing this.
